### ISSUE TITLE
Not able to write to request.write

### ISSUE THREAD

**Issue by rileymd88** [miralemd/qlik-sse#2]
For some reason I am unable to write information back within one of my functions. If I log the request before writing the data back I see the following which I suspect is my reason `writable: false`

Here is the function:
```
function GetAppMasterItems(request) {
  request.on('data', async function (bundle) {
    console.log(1);
    let tmpItems = []
    let finalItems = []
    async function getData(row) {
      return new Promise(async function (resolve, reject) {
        let masterItems = [];
        let appId = row.duals[0].strData;
        let onlyQwikMaster = row.duals[1].strData;
        let app = await global.openDoc(appId);
        let allInfos = await app.getAllInfos();
        for (var i = 0; i < allInfos.length; i++) {
          if (allInfos[i].qType == 'measure') {
            let measure = await app.getMeasure(allInfos[i].qId);
            let measureLayout = await measure.getProperties();
            if (onlyQwikMaster == 'true') {
              if (typeof measureLayout.qMetaDef.masterId != 'undefined') {
                masterItems.push(
                  [
                    measureLayout.qMetaDef.masterId,
                    "measure",
                    measureLayout.qMeasure.qDef,
                    measureLayout.qMeasure.qLabel,
                    measureLayout.qMetaDef.title,
                    measureLayout.qMetaDef.description,
                    measureLayout.qMeasure.coloring.baseColor.color,
                    appId
                  ]
                )
              }
            }
            else {
              masterItems.push(
                [
                  measureLayout.qMetaDef.masterId,
                  "measure",
                  measureLayout.qMeasure.qDef,
                  measureLayout.qMeasure.qLabel,
                  measureLayout.qMetaDef.title,
                  measureLayout.qMetaDef.description,
                  measureLayout.qMeasure.coloring.baseColor.color,
                  appId
                ]
              )
            }
          }
          if (allInfos[i].qType == 'dimension') {
            let dimension = await app.getDimension(allInfos[i].qId);
            let dimensionLayout = await dimension.getProperties();

            if (onlyQwikMaster == 'true') {
              if (typeof dimensionLayout.qMetaDef.masterId != 'undefined') {
                masterItems.push(
                  [
                    dimensionLayout.qMetaDef.masterId,
                    "dimension",
                    dimensionLayout.qDim.qFieldDefs[0],
                    dimensionLayout.qDim.qLabelExpression,
                    dimensionLayout.qDim.title,
                    dimensionLayout.qDim.descriptionExpression.qStringExpression.qExpr,
                    dimensionLayout.qDim.coloring.baseColor.color,
                    appId
                  ]
                )
              }
            }
            else {
              masterItems.push(
                [
                  dimensionLayout.qMetaDef.masterId,
                  "dimension",
                  dimensionLayout.qDim.qFieldDefs[0],
                  dimensionLayout.qDim.qLabelExpression,
                  dimensionLayout.qDim.title,
                  dimensionLayout.qDim.descriptionExpression.qStringExpression.qExpr,
                  dimensionLayout.qDim.coloring.baseColor.color,
                  appId
                ]
              )
            }
          }
        }
        resolve(masterItems)
      })
    }

    for(var r = 0; r<bundle.rows.length;r++) {
      let data = await getData(bundle.rows[r]);
      tmpItems.push(data);
      console.log(2);
    }
    var test = [];
    for(var one = 0; one< tmpItems.length; one++) {
      for(var two = 0; two < tmpItems[one].length;two++) {
        for(var three = 0; three < tmpItems[one][two].length; three++) {
          test.push({strDate: tmpItems[one][two][three]})
        }
      }
    }
    console.log(3, test);
    console.log(4);
    console.log(request);
    request.write({ "rows": [{ "duals": [{ "strData": "Sucess!" }] }] });
  })
}
```

**Comment by miralemd** [comment]
hmm, you're using async/promise which I haven't tried at all. It could be a race condition where the `end` is called and stream closed before your promises have resolved. Try moving the line https://github.com/miralemd/qlik-sse/blob/master/lib/index.js#L29 last into your own function, or test `write` without any use of async await.

**Comment by RobWunderlich** [comment]
As @miralemd suggested, when using await the request.end() will get called too early.  I resolved the issue for myself by adding an async property to the function config that drives a conditional request.end(). https://github.com/RobWunderlich/qlik-sse/commit/be4bc04ab3ca655bed5f9a2f0c76d5ee054d87eb
@miralemd do you want to accept a PR for this? Or is this too specialized?

**Comment by miralemd** [comment]
fixed by https://github.com/miralemd/qlik-sse/commit/233e014a7bdd755ec49a5c7d15b2a35ce2541e33

**Comment by rileymd88** [comment]
@RobWunderlich & @miralemd Thanks for the update. My code still does not seem to want to handle using async. Here is a super easy example which still has request.end() calling too early. Any ideas?

```
function Test(request) {
  function waitUntil(i) {
    return new Promise(function(resolve, reject){
        setTimeout(() => {
          resolve(i);
        }, 500);
    });
  }
  request.on('data', async function (bundle) {
    console.log('data');
    let list = [];
    for(let i = 0; i < 10; i++) {
       console.log(i);
       let resp = await waitUntil(i);
       list.push(resp);
    }
    console.log('writing...');
    request.write({ "rows": [{ "duals": [{ "strData": list.toString() }] }] });
  });
}
```

**Comment by RobWunderlich** [comment]
@rileymd88 The async detection expects your primary function to be marked async. So make it "async function Test(request)"

**Comment by rileymd88** [comment]
@RobWunderlich Ahh ok that worked! I had to also adjust my code at the end and write `request.end()` after `request.write(...)`
